### PR TITLE
Add "shs" for spawnProcess instead of spawnShell

### PR DESCRIPTION
**Pull request by mattthhh**

### CODE REVIEW

**Comment by lesderid** [comment]
Why "shs"? That seems to imply the opposite.

I also can't find it in the original keynav, so I'm a bit weary. What use case does this solve?

**Comment by mattthhh** [comment]
> Why "shs"? That seems to imply the opposite.

No specific reason, but i don't find acronym for that

> I also can't find it in the original keynav, so I'm a bit weary. What use case does this solve?

The reason is when i want to start a graphical app with "sh", the cmd prompt still stays open, and that a bit annoying

**Comment by lesderid** [comment]
> > I also can't find it in the original keynav, so I'm a bit weary. What use case does this solve?
> 
> The reason is when i want to start a graphical app with "sh", the cmd prompt still stays open, and that a bit annoying

If that's all you want, I suggest using `sh "cmd /c start <gui-app>"`, e.g. `v sh "cmd /c start notepad"` to launch `notepad` with the `v` key without a persistent `cmd` window.

Closing for now.

> > Why "shs"? That seems to imply the opposite.
> 
> No specific reason, but i don't find acronym for that

If you still have a good reason for this command, and therefore breaking compatibility with keynav, please find a better command name, prefix it with `x-` (as with https://github.com/lesderid/keynavish/issues/15#issuecomment-1366068075), and make a new PR with a proper commit message.

**Comment by lesderid** [comment]
I might also consider a PR that simply adds `Config.suppressConsole` to `spawnShell`.

Edit: In this case, I would prefer a https://github.com/lesderid/keynavish/labels/compatibility issue being filed for this first, to be referenced in the commit.

**Comment by mattthhh** [comment]
Okay, i'm still a begginer in Windows CMD and other things, thank you for your replies.

**Pull request closed without merging**
